language: android

jdk:
  # Jdk version used by your project
  - oraclejdk8

sudo: false

android:
  components:
    # The BuildTools version used by your project
    - build-tools-25.0.2
    - android-25
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - extra-google-google_play_services
      # Specify at least one system image, if you need to run emulator(s) during your tests
    - sys-img-armeabi-v7a-google_apis-21
    - sys-img-armeabi-v7a-google_apis-25

install:
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout;1.0.2"
  - echo yes | sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"

before_script:
    - echo no | android create avd --force --name test --target android-25 --abi google_apis/armeabi-v7a
    - emulator -avd test -no-audio -no-window -no-boot-anim -engine classic &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &
    
script:
    - ./gradlew connectedCheck
